sudo: required
services: 
  - docker

before_install:
  - docker build -t haiderbhanpurawala/docker-demo -f Dockerfile.dev .

script:
  - docker run -e CI=true haiderbhanpurawala/docker-demo npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-882130000382"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
# Comment out the deploy section for now