sudo: required
services: 
  - docker

before_install:
  - docker build -t haiderbhanpurawala/docker-demo -f Dockerfile.dev .

script:
  - docker run -e CI=true haiderbhanpurawala/docker-demo npm run test
